#!/bin/bash
n=4
i=0
while ((i<$n))
do
  echo $i
  ((i++))
done

n=5
i=0
while [ $i -lt $n ]
do
  echo $i
  ((i++))
done

i=0
while ((1))
do
  echo $i
  ((i++))
  if (($i>10)); then break; fi
done

seq 0.0 0.1 1.0| \
while read s
do
  echo $s
done

while read s
do
  echo $s
done


