#!/bin/bash
n=$1
for((i=0;i<$n;i++));
do
#  let j=$i+1 # +++
  j=$(($i+1))
  echo $j

#  if [ $j -lt 3 ]; then #+++ 
#    echo "<3"
#  else
#    echo ">=3"
#  fi

#  if [ $j -lt $2 ]; then echo "<$2"; else echo ">=$2"; fi #+++
#  if test $j -lt $2 ; then echo "<$2"; else echo ">=$2"; fi #+++
  if (( $j<$2 )); then echo "<$2"; else echo ">=$2"; fi #+++

done
